name: Build and Publish image to Docker Hub
on: 
  [workflow_dispatch]
jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: docker build ./api/ -t heemansh/devops-qr-code-api:latest
      - name: push image to docker hub
        run: |
          docker login -u heemansh -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push heemansh/devops-qr-code-api:latest
      
